site_name: Terraform Intensivo
site_url: https://nataliagranato.github.io/intensive-terraform
repo_url: https://github.com/nataliagranato/intensive-terraform
theme:
  name: material
  language: pt-BR

plugins:
  - social
  - search
