name: Terraform CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Find Terraform directories
        run: |
          echo "tf_dirs<<EOF" >> $GITHUB_ENV
          find . -type f -name '*.tf' -exec dirname {} \; | sort -u | xargs
          echo "EOF" >> $GITHUB_ENV

      - name: Terraform fmt
        run: |
          for dir in ${{ env.tf_dirs }}; do
            terraform fmt -check -recursive "$dir"
          done

      - name: Terraform validate
        run: |
          for dir in ${{ env.tf_dirs }}; do
            cd "$dir"
            terraform init -backend=false
            terraform validate
            cd -
          done

      - name: Success Message
        run: echo "O projeto Terraform foi formatado e validado com sucesso!"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
